import Image from "next/image";
import "./globals.css";
import { Toaster } from "@/components/toaster";
import { Button } from "@/components/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/popover";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white">
        <nav className="fixed w-full backdrop-blur-sm bg-[rgba(255,255,255,0.45)] z-50">
          <div className="max-w-xs md:max-w-screen-md xl:max-w-screen-xl m-auto flex justify-between h-[5rem] font-bold items-center border-b border-b-zinc-200">
            <div className="flex">
              <Image
                loading="eager"
                className="mr-8"
                src={"/uncover-dark-main-logo.svg"}
                width={159}
                height={23}
                alt="uncover-light-main-logo"
              />
            </div>
            {/* <div className="hidden md:flex font-medium text-sm">
              <Button
                variant={"ghost"}
                className="h-[32px] w-[99px] bg-white text-[#232323] border-2 border-[#232323] rounded-md mr-4 font-medium text-[14px]"
              >
                Sign In
              </Button>
              <Button className="h-[32px] w-[156px] text-white bg-[#232323] rounded-md font-medium text-[14px]">
                Request acccess
              </Button>
            </div>
            <div className="flex md:hidden">
              <Popover>
                <PopoverTrigger>Open</PopoverTrigger>
                <PopoverContent>
                  Place content for the popover here.
                </PopoverContent>
              </Popover>
            </div> */}
          </div>
        </nav>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
